  
version: 1.0.{build}
configuration: Debug
platform: Any CPU
before_build:
- cmd: nuget restore ./Klingon_Desafio.sln
build:
  project: Klingon/Klingon_Desafio.csproj
  verbosity: normal
test_script:
- cmd: cd Klingon.Test
- cmd: dotnet test